version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/go/src/github.com/leeprovoost/go-rest-api-template
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: codedeploy-scripts/application_stop.sh
      timeout: 300
  AfterInstall:
    - location: codedeploy-scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: codedeploy-scripts/application_start.sh
      timeout: 300
